# Generated by Django 5.1.7 on 2025-04-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_inventario', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignada', 'Asignada'), ('en_mantenimiento', 'En Mantenimiento'), ('fuera_de_servicio', 'Fuera de Servicio')], default='disponible', max_length=50)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='produccion_inventario.empleado')),
            ],
        ),
    ]
