# Generated by Django 5.1.7 on 2025-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_inventario', '0004_alter_userprofile_rol_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombres',
        ),
        migrations.AddField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(default='TEMP_ID', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
