# Generated by Django 5.1.7 on 2025-04-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_inventario', '0005_rename_apellidos_empleado_nombre_and_more'),
    ]

    operations = [
    ]
