# Generated by Django 5.1.7 on 2025-04-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_inventario', '0007_fix_duplicate_idscls'),
    ]

    operations = [
    ]
